name: Demo1

trigger:
  branches:
    include:
    - master
  paths:
    include:
      - /demo1/*

variables:
- name: DeploymentName
  value: 'Demo1'
- name: resourceGroupName
  value: 'rg-bicep-devops-demo'
- name: ServiceConnection
  value: 'mi-bicep-devops'
- name: TemplateParameterFile
  value: 'demo1-devops.bicepparam'

pool:
  vmImage: ubuntu-latest

stages:
- stage: Validate
  jobs:
  - job: Validate
    steps:
    - task: AzurePowerShell@5
      name: Validate
      inputs:
        azureSubscription: $(ServiceConnection)
        ScriptType: 'InlineScript'
        Inline: 'Test-AzResourceGroupDeployment -ResourceGroupName $(resourceGroupName) -TemplateParameterFile $(TemplateParameterFile) -Verbose'
        azurePowerShellVersion: 'LatestVersion'
        pwsh: true
- stage: WhatIf
  jobs:
  - job: WhatIf
    steps:
    - task: AzurePowerShell@5
      name: WhatIf
      inputs:
        azureSubscription: $(ServiceConnection)
        ScriptType: 'InlineScript'
        Inline: 'New-AzResourceGroupDeployment -Name $(DeploymentName) -ResourceGroupName $(resourceGroupName) -TemplateParameterFile $(TemplateParameterFile) -WhatIf -Verbose'
        azurePowerShellVersion: 'LatestVersion'
        pwsh: true
- stage: Deploy
  dependsOn: WhatIf
  jobs:
  - deployment:
    displayName: Deploy
    environment: Production
    strategy:
     runOnce:
       deploy:
        steps:
        - checkout: self
        - task: AzurePowerShell@5
          name: Deploy
          inputs:
            azureSubscription: $(ServiceConnection)
            ScriptType: 'InlineScript'
            Inline: 'New-AzResourceGroupDeployment -Name $(DeploymentName) -ResourceGroupName $(resourceGroupName) -TemplateParameterFile $(TemplateParameterFile) -Verbose'
            azurePowerShellVersion: 'LatestVersion'
            pwsh: true